default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99


3DBall:
    normalize: true
    batch_size: 64
    buffer_size: 12000
    summary_freq: 12000
    time_horizon: 1000
    lambd: 0.99
    beta: 0.001

3DBallHard:
    normalize: true
    batch_size: 1200
    buffer_size: 12000
    summary_freq: 12000
    time_horizon: 1000
    max_steps: 5.0e6
    beta: 0.001
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.995

ThiefLearning:
    normalize: true
    batch_size: 128
    buffer_size: 12000
    summary_freq: 12000
    time_horizon: 1000
    hidden_units: 256
    max_steps: 8.0e6
    beta: 0.001

PlayerThief:
    trainer: ppo

    # Trainer configs common to PPO/SAC (excluding reward signals)
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    normalize: false
    num_layers: 2
    time_horizon: 128
    summary_freq: 20000
    vis_encoder_type: simple
    init_path: null

    
    # PPO-specific configs
    beta: 1.0e-2
    epsilon: 0.2
    lambd: 0.99
    num_epoch: 3
    threaded: true

    # memory
    use_recurrent: false
    sequence_length: 64
    memory_size: 128

  # behavior cloning
    behavioral_cloning:
        demo_path: Demos/PlayerDemo.demo
        strength: 0.5
        steps: 150000
        batch_size: 512
        num_epoch: 3
        samples_per_update: 0

    # rewards
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

    # GAIL
    gail:
        strength: 0.5
        gamma: 0.99
        demo_path: Demos/PlayerDemo.demo
            
    # curiosity module
    curiosity:
      strength: 0.01
      gamma: 0.99
      encoding_size: 256
      learning_rate: 3.0e-4

Player:
    trainer: ppo

    # Trainer configs common to PPO/SAC (excluding reward signals)
    batch_size: 2048
    buffer_size: 20480
    hidden_units: 256
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e6
    normalize: true
    num_layers: 3
    time_horizon: 1024
    summary_freq: 60000
    vis_encoder_type: simple
    init_path: null

    
    # PPO-specific configs
    beta: 5.0e-4
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    threaded: true

    # memory
    use_recurrent: false
    sequence_length: 64
    memory_size: 128

    # rewards
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.995

    # curiosity module
    curiosity:
      strength: 0.02
      gamma: 0.995
      encoding_size: 256
      learning_rate: 1.0e-3